# Generated by Django 4.2.7 on 2023-12-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('mail', models.CharField(max_length=50, verbose_name='mail')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Compoany',
                'verbose_name_plural': 'Compoanys',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('birth', models.DateField(verbose_name='date of birth')),
                ('is_male', models.BooleanField(verbose_name='is_male')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creating_date', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.employee', verbose_name='Employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hire.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creating_date', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.company', verbose_name='Employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='hire.post', verbose_name='Post')),
                ('resumes', models.ManyToManyField(to='hire.resume', verbose_name='vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancys',
            },
        ),
        migrations.CreateModel(
            name='Recruter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('birth', models.DateField(verbose_name='date of birth')),
                ('is_male', models.BooleanField(verbose_name='is_male')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruters', to='hire.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Recruter',
                'verbose_name_plural': 'Recruters',
            },
        ),
    ]
