# Generated by Django 5.0.1 on 2024-01-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_remove_employee_login_remove_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compoany', 'verbose_name_plural': 'Compoanies'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hire.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='hire.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='resumes',
            field=models.ManyToManyField(to='hire.resume', verbose_name='resumes'),
        ),
    ]
