# Generated by Django 5.0.1 on 2024-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_alter_company_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resumes',
            field=models.ManyToManyField(null=True, to='hire.resume', verbose_name='resumes'),
        ),
    ]
