# Generated by Django 5.0.1 on 2024-01-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_alter_vacancy_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resumes',
            field=models.ManyToManyField(default=None, to='hire.resume', verbose_name='resumes'),
        ),
    ]
