# Generated by Django 5.0.1 on 2024-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_alter_vacancy_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='resumes',
            field=models.ManyToManyField(blank=True, to='hire.resume', verbose_name='resumes'),
        ),
    ]
