# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthification.proto\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"O\n\x0fRegisterRequest\x12\r\n\x05login\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x0c\n\x04type\x18\x04 \x02(\t\"\x19\n\nKeyMessage\x12\x0b\n\x03key\x18\x01 \x02(\t\"4\n\tUserReply\x12\n\n\x02id\x18\x01 \x02(\x03\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x0c\n\x04type\x18\x04 \x02(\t2\x89\x01\n\x0e\x41uthentication\x12%\n\x05Login\x12\r.LoginRequest\x1a\x0b.KeyMessage\"\x00\x12+\n\x08Register\x12\x10.RegisterRequest\x1a\x0b.KeyMessage\"\x00\x12#\n\x06\x41\x63\x63\x65rt\x12\x0b.KeyMessage\x1a\n.UserReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=23
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_REGISTERREQUEST']._serialized_start=72
  _globals['_REGISTERREQUEST']._serialized_end=151
  _globals['_KEYMESSAGE']._serialized_start=153
  _globals['_KEYMESSAGE']._serialized_end=178
  _globals['_USERREPLY']._serialized_start=180
  _globals['_USERREPLY']._serialized_end=232
  _globals['_AUTHENTICATION']._serialized_start=235
  _globals['_AUTHENTICATION']._serialized_end=372
# @@protoc_insertion_point(module_scope)
