name: CICD
on: 
    push:
        branches: main
    pull_request: 
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --no-cache --exclude **/migrations/ ./server

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: docker compose run --entrypoint pytest server
  
  deploy:
      needs: [tests, linter]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' }}
      steps:
        - uses: actions/checkout@v4
        - name: put key
          env: # Or as an environment variable
            KEY: ${{ secrets.SSHKEY }}
          run: |
           mkdir -p ~/.ssh/
           ssh-keyscan -H 178.253.40.223 >> /home/runner/.ssh/known_hosts
           echo $KEY > /home/runner/.ssh/id_rsa
           sudo chmod 600 /home/runner/.ssh/id_rsa
        - name: deploy
          run: |
           docker context create remote --docker "host=ssh://root@178.253.40.223"
           docker-compose --context remote up build -d --build --force-recreate
        


